language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="f6c22e38-1ce5-43bf-90da-b31c00c3bde5"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -emelyanov.am@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
